general.import = ["~/.config/colors.toml"]
[window]
#decorations = "None"
opacity = 0.666
blur = true

[window.dimensions]
columns = 120
lines = 30

[colors.primary]
background = "#1e1e2e" 

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[terminal.shell]
program = "zsh"
# program = "/Users/harveyfa/bin/tmux"
# args = ["new-session", "-A", "-D", "-s", "main"]

[scrolling]
history = 1000

[env]
TERM = "xterm-256color"
